POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "admin@burger.com",
    "password": "123456"
}


GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGJ1cmdlci5jb20iLCJpYXQiOjE2NTUyMjE4MTEsImV4cCI6MTY1NTIyNTQxMSwic3ViIjoiMSJ9.eQHATUFREpe6mvd3FmPdLEM-R0tHAMr0mPUhJsahxoQ

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzMzkwOSwiZXhwIjoxNjUwMjM3NTA5LCJzdWIiOiIyIn0.nS99u-MBatZHbexMUenwsGdS8oV55BIaGwI6PSP7BC8

GET http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWZAYnVyZ2VyLmNvbSIsImlhdCI6MTY1NDExMzU4OSwiZXhwIjoxNjU0MTE3MTg5LCJzdWIiOiIzIn0.pkRrswoOOly2R3jB9wTTHWRvKHCXFlwCgP5Oq96t09Y

PATCH http://localhost:8080/orders/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWZAYnVyZ2VyLmNvbSIsImlhdCI6MTY1NDYzNzcxOCwiZXhwIjoxNjU0NjQxMzE4LCJzdWIiOiIzIn0.NSQUeyGjlmGz-fEhAhKGseaV-0Lluz-Sc7rOVsOKQF8

{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}